FROM python:3.10.6
RUN apt-get update && apt-get upgrade -y
RUN mkdir -p /app/web
WORKDIR /app/web
COPY ./requirements.txt /app/web
COPY ./uwsgi.ini /app/web
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD ["uwsgi", "--ini", "uwsgi.ini"]